article: https://github.com/bigclownlabs/bcf-kit-sigfox-pulse-counter/blob/master/README.md
assembly:
  - name: BigClown Sensor Module
  - name: BigClown Sigfox Module
  - name: BigClown Core Module
  - name: BigClown Mini Battery Module
  
