article: https://github.com/bigclownlabs/bcf-kit-sigfox-pulse-counter/blob/master/README.md
assembly:
  - name: HARDWARIO Sensor Module
  - name: HARDWARIO Sigfox Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Mini Battery Module
  
